kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: mongodb
  namespace: openshift
  labels:
    samples.operator.openshift.io/managed: 'true'
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 'latest'
      annotations:
        description: 'Provides a MongoDB database on RHEL 7. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/mongodb-container/tree/master/3.4/README.md.\n\nWARNING: By selecting this tag, your application will automatically update to use the latest version of MongoDB available on OpenShift, including major version updates.'
        openshift.io/display-name: MongoDB
        openshift.io/provider-display-name: 'Red Hat, Inc.'
        tags: 'mongodb,database,hidden'
        version: 'latest'
      from:
        kind: ImageStreamTag
        name: '3.6'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Local
    - name: '3.6'
      annotations:
        description: 'Provides a MongoDB database on RHEL 7. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/mongodb-container/tree/master/3.4/README.md.\n\nWARNING: By selecting this tag, your application will automatically update to use the latest version of MongoDB available on OpenShift, including major version updates.'
        iconClass: icon-mongodb
        openshift.io/display-name: MongoDB
        openshift.io/provider-display-name: 'Red Hat, Inc.'
        tags: mongodb
        version: '3.6'
      from:
        kind: DockerImage
        name: 'registry.redhat.io/rhscl/mongodb-36-rhel7:latest'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Local
    
